name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. AWS CLI 설치
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # 3. GitHub Actions의 IP를 EC2 보안 그룹에 추가 (SSH 인바운드 규칙)
      - name: Add SSH inbound rule to EC2 security group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id sg-00238cd34b57d6565 \
            --protocol tcp \
            --port 22 \
            --cidr $(curl -s https://checkip.amazonaws.com)/32
        # 이 명령어는 현재 GitHub Actions의 퍼블릭 IP를 보안 그룹에 추가하여 SSH 접근을 허용함

      # 4. EC2로 배포 작업 수행
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ubuntu
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > SSH_PRIVATE_KEY.pem
          chmod 600 SSH_PRIVATE_KEY.pem
          ssh -i SSH_PRIVATE_KEY.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # Docker 컨테이너 업데이트 및 재시작
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF

      # 5. EC2 보안 그룹에서 인바운드 규칙 제거 (작업 완료 후 SSH 접근 제거)
      - name: Remove SSH inbound rule from EC2 security group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id sg-00238cd34b57d6565 \
            --protocol tcp \
            --port 22 \
            --cidr $(curl -s https://checkip.amazonaws.com)/32
