name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TAG=latest" >> $GITHUB_ENV
            echo "EC2_HOST=${{ secrets.EC2_HOST_PROD }}" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TAG=dev" >> $GITHUB_ENV
            echo "EC2_HOST=${{ secrets.EC2_HOST_DEV }}" >> $GITHUB_ENV
          fi

      - name: Login to Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          TAG: ${{ env.TAG }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Add SSH inbound rule
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id sg-00238cd34b57d6565 \
            --protocol tcp \
            --port 22 \
            --cidr $(curl -s https://checkip.amazonaws.com)/32

      - name: Deploy to EC2
        run: |
          echo "${SSH_PRIVATE_KEY}" > SSH_PRIVATE_KEY.pem
          chmod 600 SSH_PRIVATE_KEY.pem
          echo "EC2_HOST=${EC2_HOST}"
          echo "TAG=${TAG}"
          echo "ENV=${ENV}"

          ssh -i SSH_PRIVATE_KEY.pem -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} << EOF
            cd clab
            docker pull ghcr.io/${{ env.IMAGE_NAME }}:${TAG}
            ENV=${ENV} docker compose down
            ENV=${ENV} docker compose up -d --build
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove SSH inbound rule
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id sg-00238cd34b57d6565 \
            --protocol tcp \
            --port 22 \
            --cidr $(curl -s https://checkip.amazonaws.com)/32
